name: Greetings

on: [ pull_request_target, issues ]

jobs:
  greetings:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          issue-message: "Thank you for bringing this to our attention! We truly appreciate your input and will review it as soon as possible. Your contributions help make this project better!"
          pr-message: "Welcome and thank you for your first pull request! We're excited to review your contribution and look forward to collaborating with you on future improvements."
