name: "Pull Request Labeler"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - stage
      - production

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
